version: '3.2'

services:
  workana_php:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: workana_php
    tty: true
    volumes:
      - ./:/mercado
    restart: unless-stopped
    links:
      - 'db:db'
    networks:
      - workana
    ports:
      - '9004:9004'
  db:
    image: 'mysql:latest'
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - '3306'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: workana_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    restart: unless-stopped
    networks:
      - workana
    volumes:
      - .docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql

networks:
  workana:
    driver: bridge